"""empty message

Revision ID: 0bc364df16ea
Revises: 4b8e4473789a
Create Date: 2022-04-24 19:24:31.929077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc364df16ea'
down_revision = '4b8e4473789a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructor', 'section_id')
    op.add_column('section', sa.Column('assignedInstructor', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'section', 'instructor', ['assignedInstructor'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'section', type_='foreignkey')
    op.drop_column('section', 'assignedInstructor')
    op.add_column('instructor', sa.Column('section_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
