"""empty message

Revision ID: 0c9ae4c327c2
Revises: d513d1375048
Create Date: 2022-04-13 22:09:34.542467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9ae4c327c2'
down_revision = 'd513d1375048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section', 'sectionNumber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('sectionNumber', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
