"""empty message

Revision ID: 1421289d64f5
Revises: 7f601071c3fd
Create Date: 2022-04-17 18:05:14.602213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1421289d64f5'
down_revision = '7f601071c3fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'meeting_period', ['section_id', 'meetDay'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meeting_period', type_='unique')
    # ### end Alembic commands ###
