"""empty message

Revision ID: 4b8e4473789a
Revises: 14da9ac67a11
Create Date: 2022-04-24 19:20:27.315326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8e4473789a'
down_revision = '14da9ac67a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructor', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'instructor', 'section', ['section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instructor', type_='foreignkey')
    op.drop_column('instructor', 'section_id')
    # ### end Alembic commands ###
