"""empty message

Revision ID: 60cdea75fa8f
Revises: 1d7d69a9cfb7
Create Date: 2022-03-29 01:08:55.432384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60cdea75fa8f'
down_revision = '1d7d69a9cfb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructor', sa.Column('lastName', sa.String(length=30), nullable=False))
    op.add_column('instructor', sa.Column('firstName', sa.String(length=30), nullable=False))
    op.drop_column('instructor', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructor', sa.Column('name', sa.VARCHAR(length=30), nullable=False))
    op.drop_column('instructor', 'firstName')
    op.drop_column('instructor', 'lastName')
    # ### end Alembic commands ###
