"""empty message

Revision ID: 6b1bc517a07f
Revises: 0bc364df16ea
Create Date: 2022-04-24 19:26:01.499411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1bc517a07f'
down_revision = '0bc364df16ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'section', 'instructor', ['assignedInstructor'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'section', type_='foreignkey')
    # ### end Alembic commands ###
