"""empty message

Revision ID: 7f601071c3fd
Revises: 0c9ae4c327c2
Create Date: 2022-04-13 22:10:36.805768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f601071c3fd'
down_revision = '0c9ae4c327c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('sectionNumber', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'section', ['sectionNumber'])
    op.drop_column('section', 'number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('number', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'section', type_='unique')
    op.drop_column('section', 'sectionNumber')
    # ### end Alembic commands ###
