"""empty message

Revision ID: 8871286e952a
Revises: 661b87646022
Create Date: 2022-03-21 19:24:09.515853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8871286e952a'
down_revision = '661b87646022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_confirmation_sent_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('email_confirmed', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('email_confirmed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_confirmed_on')
    op.drop_column('user', 'email_confirmed')
    op.drop_column('user', 'email_confirmation_sent_on')
    # ### end Alembic commands ###
