"""empty message

Revision ID: 9c644be12df2
Revises: 60cdea75fa8f
Create Date: 2022-04-01 02:52:49.762493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c644be12df2'
down_revision = '60cdea75fa8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instructor_discipline_area', type_='foreignkey')
    op.create_foreign_key(None, 'instructor_discipline_area', 'instructor', ['instructor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instructor_discipline_area', type_='foreignkey')
    op.create_foreign_key(None, 'instructor_discipline_area', 'instructor', ['instructor_id'], ['id'])
    # ### end Alembic commands ###
