"""empty message

Revision ID: ad36e0507d54
Revises: d73c35011f2f
Create Date: 2022-04-01 03:47:25.109365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad36e0507d54'
down_revision = 'd73c35011f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instructor_discipline_area', type_='foreignkey')
    op.create_foreign_key(None, 'instructor_discipline_area', 'instructor', ['instructor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instructor_discipline_area', type_='foreignkey')
    op.create_foreign_key(None, 'instructor_discipline_area', 'instructor', ['instructor_id'], ['id'])
    # ### end Alembic commands ###
