"""empty message

Revision ID: d513d1375048
Revises: 632d6927c9dd
Create Date: 2022-04-13 22:06:25.399112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd513d1375048'
down_revision = '632d6927c9dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('sectionNumber', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'section', ['sectionNumber'])
    op.drop_column('section', 'number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('number', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'section', type_='unique')
    op.drop_column('section', 'sectionNumber')
    # ### end Alembic commands ###
