"""empty message

Revision ID: d73c35011f2f
Revises: 9c644be12df2
Create Date: 2022-04-01 02:54:38.561626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73c35011f2f'
down_revision = '9c644be12df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instructor_discipline_area', type_='foreignkey')
    op.create_foreign_key(None, 'instructor_discipline_area', 'instructor', ['instructor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instructor_discipline_area', type_='foreignkey')
    op.create_foreign_key(None, 'instructor_discipline_area', 'instructor', ['instructor_id'], ['id'])
    # ### end Alembic commands ###
